---
# tasks file for networking

- name: SETUP | Ensure firewalld is present.
  yum:
    name: firewalld
    state: present

- name: SETUP | Ensure firewalld is running.
  service:
    name: firewalld
    state: started
    enabled: true

- name: TRUSTED | Enable Sources
  firewalld:
    zone: trusted
    source: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.trusted.sources }}"

- name: TRUSTED | Enable Services
  firewalld:
    zone: trusted
    service: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.trusted.services }}"

- name: TRUSTED | Enable Specific Ports
  firewalld:
    zone: trusted
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.trusted.ports }}"

- name: TRUSTED | Enable Rich Rules
  firewalld:
    zone: trusted
    rich_rule: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.trusted.rich_rules }}"

- name: TRUSTED | Enable Interfaces
  firewalld:
    zone: trusted
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.trusted.interfaces }}"

- name: INTERNAL | Enable Sources
  firewalld:
    zone: internal
    source: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.internal.sources }}"

- name: INTERNAL| Enable Services
  firewalld:
    zone: internal
    service: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.internal.services }}"

- name: INTERNAL | Enable Specific Ports
  firewalld:
    zone: internal
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.internal.ports }}"

- name: INTERNAL | Enable Rich Rules
  firewalld:
    zone: internal
    rich_rule: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.internal.rich_rules }}"

- name: INTERNAL | Enable Interfaces
  firewalld:
    zone: internal
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.internal.interfaces }}"

- name: PUBLIC | Enable Sources
  firewalld:
    zone: public
    source: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.public.sources }}"

- name: PUBLIC | Enable Services
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.public.services }}"

- name: PUBLIC | Enable Specific Ports
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.public.ports }}"

- name: PUBLIC | Enable Rich Rules
  firewalld:
    zone: public
    rich_rule: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.public.rich_rules }}"

- name: PUBLIC | Enable Interfaces
  firewalld:
    zone: public
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  notify: restart firewalld
  with_items:
    - "{{ enabled_zones.public.interfaces }}"
