---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 .

platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: /sbin/init
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: testinfra
